
app_name: search.web.ch.gov.uk
group: web
weight: 900
routes:
  1: ^/alphabetical-search
  2: ^/alphabetical-search/.*
  3: ^/dissolved-search
  4: ^/dissolved-search/.*
  5: ^/advanced-search
  6: ^/advanced-search/.*
  7: /ed
  8: /ed/.*